CREATE TABLE IF NOT EXISTS `userinfo` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `ksxing` varchar(20) DEFAULT NULL,
  `ksming` varchar(40) DEFAULT NULL,
  `kspxing` varchar(40) DEFAULT NULL,
  `kspming` varchar(40) DEFAULT NULL,
  `ksxb` varchar(40) DEFAULT NULL,
  `year` varchar(4) DEFAULT NULL,
  `month` varchar(2) DEFAULT NULL,
  `day` varchar(2) DEFAULT NULL,
  `ksidtype` varchar(40) DEFAULT NULL,
  `ksidno` varchar(40) DEFAULT NULL,
  `kspwd` varchar(40) DEFAULT NULL,
  `ksremind` varchar(40) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `ksremindanswer` varchar(40) DEFAULT NULL,
  `userqh` varchar(40) DEFAULT NULL,
  `usertel` varchar(40) DEFAULT NULL,
  `kstel` varchar(40) DEFAULT NULL,
  `ksmobile` varchar(40) DEFAULT NULL,
  `ksemail` varchar(40) DEFAULT NULL,
  `wishjb` varchar(40) DEFAULT NULL,
  `wishprovince` varchar(40) DEFAULT NULL,
  `wishcity1` varchar(40) DEFAULT NULL,
  `wishcity2` varchar(40) DEFAULT NULL,
  `wishcity3` varchar(40) DEFAULT NULL,
  `tiaoji` varchar(1) DEFAULT 'y',
  `ksqq` varchar(20) DEFAULT NULL,
  `ksimgsrc` varchar(200) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=40 ;
